In [1]:
import pandas as pd

# Hi

df = pd.read_csv("ChaseTransactions.csv")
catMap = pd.read_csv("categoryMap.csv")

df.columns = df.columns.str.strip().str.lower()
catMap.columns = catMap.columns.str.strip().str.lower()

df.head()

,transaction date,post date,description,category,type,amount,memo
0,06/09/2026,06/10/2026,BLUE SHIELD CALIFORNIA,Bills & Utilities,Sale,-159.00,NaN
1,06/08/2026,06/10/2026,LOWES #03095*,Home,Sale,-186.74,NaN
2,06/08/2026,06/10/2026,LOWES #03095*,Home,Sale,-11.91,NaN
3,06/07/2026,06/09/2026,TRADER JOE S #236,Groceries,Sale,-189.42,NaN
4,06/07/2026,06/08/2026,SLOAT GARDEN CNTR #1,Home,Sale,-317.99,NaN

In [2]:
catMap.head()

,transaction date,post date,description,category,type,amount,memo,category
0,06/09/2026,06/10/2026,BLUE SHIELD CALIFORNIA,Bills & Utilities,Sale,-159.00,NaN,Medicare Premium
1,06/08/2026,06/10/2026,LOWES #03095*,Home,Sale,-186.74,NaN,NaN
2,06/08/2026,06/10/2026,LOWES #03095*,Home,Sale,-11.91,NaN,NaN
3,06/07/2026,06/09/2026,TRADER JOE S #236,Groceries,Sale,-189.42,NaN,NaN
4,06/07/2026,06/08/2026,SLOAT GARDEN CNTR #1,Home,Sale,-317.99,NaN,NaN

In [3]:
print(df.columns)

Index(['transaction date', 'post date', 'description', 'category', 'type',
       'amount', 'memo'],
      dtype='object')

In [4]:
print(df.loc[df['description'] == 'SFPUC WEB_PAY'])

Empty DataFrame
Columns: [transaction date, post date, description, category, type, amount, memo]
Index: []

In [5]:
df.head()

,transaction date,post date,description,category,type,amount,memo
0,06/09/2026,06/10/2026,BLUE SHIELD CALIFORNIA,Bills & Utilities,Sale,-159.00,NaN
1,06/08/2026,06/10/2026,LOWES #03095*,Home,Sale,-186.74,NaN
2,06/08/2026,06/10/2026,LOWES #03095*,Home,Sale,-11.91,NaN
3,06/07/2026,06/09/2026,TRADER JOE S #236,Groceries,Sale,-189.42,NaN
4,06/07/2026,06/08/2026,SLOAT GARDEN CNTR #1,Home,Sale,-317.99,NaN

In [6]:
df.loc[
    df['description'].str.contains('SFPUC ', case=False, na=False),
    'Category'
] = 'Water'

In [7]:
df.loc[
    df['description'].str.contains('BLUE SHIELD', case=False, na=False),
    'Category'
] = 'Medicare Premium'

In [8]:
df.head()

,transaction date,post date,description,category,type,amount,memo,Category
0,06/09/2026,06/10/2026,BLUE SHIELD CALIFORNIA,Bills & Utilities,Sale,-159.00,NaN,Medicare Premium
1,06/08/2026,06/10/2026,LOWES #03095*,Home,Sale,-186.74,NaN,NaN
2,06/08/2026,06/10/2026,LOWES #03095*,Home,Sale,-11.91,NaN,NaN
3,06/07/2026,06/09/2026,TRADER JOE S #236,Groceries,Sale,-189.42,NaN,NaN
4,06/07/2026,06/08/2026,SLOAT GARDEN CNTR #1,Home,Sale,-317.99,NaN,NaN

In [9]:
df.to_csv("categoryMap.csv", index=False)